//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3WN4K_beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public int dir_id { get; set; }
        public Nullable<int> num_o_awards { get; set; }
        public string main_award { get; set; }
    
        public virtual Director Director { get; set; }
    }
}
