//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3WN4K_beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Director()
        {
            this.Movies_Director = new HashSet<Movies_Director>();
        }
    
        public int ID { get; set; }
        public string dir_fname { get; set; }
        public string dir_lname { get; set; }
        public string dir_gender { get; set; }
        public Nullable<System.DateTime> dir_born { get; set; }
        public string dir_born_place { get; set; }
    
        public virtual Award Award { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movies_Director> Movies_Director { get; set; }
    }
}
