//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3WN4K_beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies_Director
    {
        public int ID { get; set; }
        public int MovieFK { get; set; }
        public int DirectorFK { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
